log service names (#1208)
so that when errors occur it's more obvious which server has the issue instead of only logging the host/port

e.g.
r2_labs.rpc.client.RpcTimeoutError: RPC timeout calling ping on tcp://magenta:7534 (service: training server)